name: 🥳 Auto Update Submodule

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [ sync-shared-submodules ]
  schedule:
    #  every day at 5:30 
      - cron:  '30 1 * * *'

env:
  COMMIT_MESSAGE: "chore: update submodules"

jobs:
  sync-shared-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: "true"
      - name: Update submodule
        run: |
          git submodule update --init --recursive --remote
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto Update Submodule"
